--- #YAML:1.0
name: Test-LectroTest
version: 0.2005
author:
  - Tom Moertel (tom@moertel.com)
abstract: Easy, automatic, specification-based tests
license: perl
generated_by: Module::Build version 0.25, without YAML.pm
