---
abstract: 'Easy, automatic, specification-based tests'
author:
  - 'Tom Moertel <tom@moertel.com>'
build_requires:
  File::Temp: 0
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300023, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Test-LectroTest
requires:
  Carp: 0
  Class::Struct: 0
  Data::Dumper: 0
  Exporter: 0
  Filter::Util::Call: 0
  POSIX: 0
  Scalar::Util: 0
  Test::Builder: 0
  constant: 0
  strict: 0
  warnings: 0
version: 0.5000
